name: fruit
version: "0.1.0.0"
category: Compiler, Language
author: Yuriy Lazarev
maintainer: unisay@users.noreply.github.com
bug-reports: unisay@users.noreply.github.com
synopsis: >
  The `fruit` command line interface.
description: >
  FRUIT - Functional Reactive programming language for the Web

copyright: Yuriy Lazarev
github: Unisay/fruit
license: MIT
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wpartial-fields
  - -Wtabs
  - -Wmissing-local-signatures
  - -fhelpful-errors
  - -fprint-expanded-synonyms
  - -fwarn-unused-do-bind
  - -Werror=incomplete-patterns

default-extensions: OverloadedStrings

dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude, Relude.Unsafe)

executables:
  fruitc:
    main: Main.hs
    source-dirs: exe/fruitc
    dependencies:
      - fruit
      - optparse-applicative
      - pathtype
      - pretty-show
      - with-utf8
  fruiti:
    main: Main.hs
    source-dirs: exe/fruiti
    ghc-options:
      - -threaded
    dependencies:
      - containers
      - exceptions
      - fruit
      - mtl
      - with-utf8
      - pretty-show
      - prettyprinter
      - prettyprinter-ansi-terminal
      - repline
      - text
      - transformers
      - typed-process

library:
  source-dirs:
    - src
  dependencies:
    - array
    - bytestring
    - deepseq
    - ghc-prim
    - pathtype
    - pretty-show
    - prettyprinter
    - prettyprinter-ansi-terminal
    - text
    - transformers
    - mtl
    - unbound
    - uniplate
    - utf8-string

tests:
  spec:
    main: Main.hs
    source-dirs:
      - test
    dependencies:
      - fruit
      - filepath
      - pretty-show
      - prettyprinter
      - hedgehog
      - hspec
      - hspec-expectations-pretty-diff
      - tasty
      - tasty-hspec
      - tasty-golden
      - with-utf8
      - uniplate
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-missing-local-signatures
