name: frut
version: "0.1.0.0"
category: Compiler, Language
author: Yuriy Lazarev
maintainer: unisay@users.noreply.github.com
bug-reports: unisay@users.noreply.github.com
synopsis: >
  The `frut` command line interface.
description: >
  FRUT - Functional Reactive programming language for the Web

copyright: Yuriy Lazarev
github: Unisay/frut
license: MIT
extra-source-files:
  - README.md

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
  - -Wpartial-fields
  - -Wtabs
  - -Wmissing-local-signatures
  - -fhelpful-errors
  - -fprint-expanded-synonyms
  - -fwarn-unused-do-bind
  - -Werror=incomplete-patterns

default-extensions: OverloadedStrings

dependencies:
  - name: base
    mixin:
      - hiding (Prelude)
  - name: relude
    mixin:
      - (Relude as Prelude, Relude.Unsafe)

executables:
  frutc:
    main: Frutc.hs
    ghc-options: -main-is Frutc
    source-dirs: exe
    dependencies:
      - frut
      - optparse-applicative
      - pathtype
      - pretty-show

library:
  source-dirs:
    - src
  exposed-modules:
    - Language.Frut.Data.InputStream
    - Language.Frut.Data.Position
    - Language.Frut.Lexer
    - Language.Frut.Parser.Monad
    - Language.Frut.Parser
    - Language.Frut.Syntax.AST
    - Language.Frut.Syntax.Tok
  other-modules:
    - Language.Frut.Alex
    - Language.Frut.Data.Ident
    - Language.Frut.Parser.Internal
  dependencies:
    - array
    - deepseq
    - bytestring
    - pathtype
    - text
    - utf8-string

tests:
  spec:
    main: Driver.hs
    source-dirs:
      - test
    dependencies:
      - frut
      - filepath
      - pretty-show
      - tasty
      - tasty-golden
      - tasty-discover
      - tasty-hedgehog
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
      - -Wno-missing-local-signatures
